version: '3.6'
services:
  php_88:
    image: 'chialab/php-dev:7.2-apache'
    volumes:
      - '.:/var/www/html'
      - './docker/webservice/000-default.conf:/etc/apache2/sites-available/000-default.conf'