version: '3.6'
services:
  php_88:
    image: 'chialab/php-dev:7.3-apache'
    volumes:
      - '.:/var/www/html'
      - './docker/webservice/000-default.conf:/etc/apache2/sites-available/000-default.conf'
    depends_on:
      - database_88
  database_88:
    image: 'mariadb'
    environment:
      - MYSQL_ROOT_PASSWORD=root
  adminer_88:
    image: 'adminer'
    environment:
      - ADMINER_DEFAULT_SERVER=database_88
      - ADMINER_DESIGN=brade